<?php

return array (
  'name' => '我的网站',
  'beian' => '',
  'cdnurl' => '',
  'version' => '1.0.3',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => '测试',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'botset' => '机器人设置',
    'meilisearchset' => 'meilisearch设置',
    'aiset' => 'ai设置',
    'groupset' => '群组设置',
    'payset' => '支付设置',
    'RabbitMQset' => 'RabbitMQset',
    'kefuset' => '客服设置',
    'licenseset' => '授权设置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '',
  'mail_smtp_pass' => '',
  'mail_verify_type' => '2',
  'mail_from' => '',
  'attachmentcategory' => 
  array (
    'category1' => '分类一',
    'category2' => '分类二',
    'custom' => '自定义',
  ),
  'bottoken' => '7070944231:AAG4By-Y3wL38dIKQfwKMRZE3h3X8B190oA',
  'manticorehost' => '212.85.25.113',
  'manticoreport' => '9306',
  'isopenai' => '1',
  'meiliurl' => 'http://127.0.0.1:7700',
  'meili_key' => 'DjXdjd87qoX62PY35ryur_NS4R1hl-SlHlfHELNnw_U',
  'openai_key' => 'sk-gTywYrbROyxAUaqo2cD91eEcCb2d4cC0924c570f73De639f',
  'cate_mode' => 'text-davinci-003',
  'audit_mode' => 'gpt-4',
  'language_ldentification_mode' => 'gpt-4',
  'tokenpay_url' => 'https://tokenpay.8br.dpdns.org',
  'kefu_url' => 'http://crmchat.8br.dpdns.org/service/login/index.html',
  'kefu_username' => 'https://t.me/buzhiguiqi',
  'default_lang' => 'zh-cn',
  'partner' => '3000',
  'tokenpay_key' => '666666',
  'order_expire' => '10',
  'deposit_methods' => '1',
  'pay_currency' => 'USDT_TRC20,TRX',
  'license_code' => 'CCAEE2C4-CDAE-834D-D78C-D37570CAAF87',
  'groups_audit' => 'ai_artificial',
  'default_kd' => '5',
  'audit_method' => 'direct_review',
  'private_delete' => 'edit_message',
  'select_icon' => '✅',
  'customer_time' => '60',
  'customer_hook' => 'http://crmchat.8br.dpdns.org/',
  'fastgpt_url' => 'https://api.fastgpt.in',
  'fastgpt_datasetId' => '68245cf44d030c8e71cc8e29',
  'fastgpt_key' => 'fastgpt-j1G1LP93AUNyg6tfouwJuBeggLkT4cxlZ7MzoQLNGpKoXuSQWv35',
  'fastgpt_appid' => '68245db852558308d8abc8c0',
  'RabbitMQ_host' => '212.85.25.113',
  'RabbitMQ_port' => '5672',
  'RabbitMQ_user' => 'admin',
  'RabbitMQ_password' => 'D77L6mcEyDqtMWqx',
  'RabbitMQ_vhost' => 'bthost',
  'telegramIcon' => '{"all":"#⃣","shop":"🏪","supergroup":"👥","channel":"📢","photo":"🖼️","video":"🎬","music":"🎵","document":"📄","link":"🔗","bot":"🤖","group":"👥"}',
  'prohibited_words' => '测试',
  'advkey_count' => '5',
  'default_keyadv_amount' => '100',
  'get_group_info' => 'http://127.0.0.1:5000/api/entity?username=',
  'invitereward' => '{"textbox":0.18,"dirpush":0.1,"onedirpush":0.02,"opensearch":0.03,"onesearch":0.0036,"twosearch":0.0009}',
  'embody' => 'bot',
  'business_id' => '1',
);
